- name: Install sudo package
  yum: name=sudo state=present

- name: Add superuser group
  group: name=superuser state=present

- name: Allow superuser group to do anything without password
  lineinfile:
    line: "%superuser ALL=(ALL) NOPASSWD:ALL"
    regexp: "^\\s*%superuser\\s+ALL\\s*="
    dest: /etc/sudoers
    state: present
    validate: "visudo -cf %s"